// serviceCategories.js
export const serviceCategories = {
  Health: [
    "Dentist",
    "Doctor",
    "Clinic",
    "Physiotherapist",
    "Therapist",
    "Veterinarian",
    "Optometrist",
    "Chiropractor",
    "Psychologist",
    "Nutritionist",
    "Laboratory",
    "Phlebotomist",
    "Radiologist",
    "Speech Therapist",
    "Acupuncturist",
    "Midwife",
    "Medical Specialist",
  ],
  Beauty: [
    "Salon",
    "Hairdresser",
    "Barber",
    "Spa",
    "Massage Therapist",
    "Makeup Artist",
    "Nail Technician",
    "Esthetician",
    "Cosmetologist",
    "Tattoo Artist",
  ],
  Accommodation: [
    "Hotel",
    "Guest House",
    "Hostel",
    "Bed and Breakfast",
    "Resort",
    "Vacation Rental",
    "Motel",
  ],
  Food: [
    "Restaurant",
    "Cafe",
    "Catering",
    "Bakery",
    "Food Truck",
    "Bar",
    "Juice Bar",
  ],
  Auto: [
    "Mechanic",
    "Car Wash",
    "Auto Body Repair",
    "Tire Shop",
    "Car Rental",
    "Driving School",
  ],
  Fitness: [
    "Gym",
    "Personal Trainer",
    "Yoga Studio",
    "Pilates Studio",
    "Dance Studio",
    "Martial Arts Dojo",
    "CrossFit Box",
    "Swimming Pool",
  ],
  Professional: [
    "Lawyer",
    "Consultant",
    "Accountant",
    "Financial Advisor",
    "Real Estate Agent",
    "Notary",
    "Therapist (Counseling)",
    "Career Coach",
    "Tutor",
    "Interpreter",
    "Wedding Planner",
  ],
  Education: [
    "Tutoring Center",
    "Music Teacher",
    "Language School",
    "Driving Instructor",
    "Dance Teacher",
    "Art Classes",
    "Test Preparation",
  ],
  Events: [
    "Event Venue",
    "Photographer",
    "Videographer",
    "DJ",
    "Caterer",
    "Party Planner",
    "Florist",
  ],
  HomeServices: [
    "Plumber",
    "Electrician",
    "House Cleaner",
    "Landscaper",
    "Pest Control",
    "Handyman",
    "Painter",
  ],
};
